[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "2HutoV77VksPtWycEpXcsKuxaC1VC8yuUbPxyGMJYRu8"

[programs.devnet]
marketplace = "2HutoV77VksPtWycEpXcsKuxaC1VC8yuUbPxyGMJYRu8"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
